version: "3"

networks:
  school:

services:
  school_httpd:
    image: httpd:2.4.52-alpine
    container_name: school_httpd
    ports:
      - "8082:80"
    volumes:
      - ./:/var/www/html/
      - ./docker/.env.example:/var/www/html/.env
      - ./docker/httpd.conf:/usr/local/apache2/conf/httpd.conf
    depends_on:
      - mysql
      - php
    networks:
      - school

  php:
    build:
      context: ./docker
      dockerfile: Dockerfile
    container_name: school_php
    ports:
      - "9000:9000"
    volumes:
      - ./:/var/www/html/
      - ./docker/.env.example:/var/www/html/.env
      - ./docker/httpd.conf:/usr/local/apache2/conf/httpd.conf
    networks:
      - school

  mysql:
    image: mysql:8.0.28
    container_name: school_mysql
    ports:
      - "3309:3306"
    volumes:
      - ./docker/mysql_backup:/var/lib/mysql
    environment:
      MYSQL_DATABASE: 'school'
      MYSQL_ROOT_PASSWORD: admin
    networks:
      - school
